# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }: {
  ###############################################

  # THE BELOW CODE IS COPIED FROM THE AUTO-GENERATED 'configuration.nix'.
  # IT MAY CONTAIN EDITS.
  # Bootloader.

  boot = {
    loader = {
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
    };
  };

  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It‘s perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  # Before changing this value read the documentation for this option
  # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
  system.stateVersion = "23.05"; # Did you read the comment?

  ###############################################

  # THE BELOW CODE IS COPIED FROM THE AUTO-GENERATED 'hardware-configuration.nix'.
  # IT MAY CONTAIN EDITS.

  imports = [(modulesPath + "/installer/scan/not-detected.nix")];

  # boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = ["amdgpu"];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/0f2bfbbf-d5f2-4595-8172-99ea3fd33765";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/072C-10A7";
    fsType = "vfat";
  };

  fileSystems."/mnt/red" = {
    device = "/dev/disk/by-uuid/182dc111-33a9-4853-abd7-867f05121aa8";
    fsType = "btrfs";
    options = ["nosuid" "nodev" "nofail" "x-gvfs-show"];
  };

  fileSystems."/mnt/extra" = {
    device = "/dev/disk/by-uuid/6649d4db-5724-4d8e-b8da-acf4aeaf06d3";
    fsType = "btrfs";
    options = ["nosuid" "nodev" "nofail" "x-gvfs-show"];
  };

  fileSystems."/mnt/windows" = {
    device = "/dev/disk/by-uuid/7ADEE1C1DEE175B3";
    fsType = "ntfs-3g";
    options = ["rw" "uid=1000" "x-gvfs-show"];
  };

  swapDevices = [{device = "/dev/disk/by-uuid/e0455362-aa9f-4dca-92f9-a9a75bcb8053";}];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp37s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp38s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
